image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: install-dependencies
    before: |
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      printf 'export PATH="/workspace/ds201-lab07/node1/bin:$PATH"' >> $HOME/.bashrc
    init: |
      curl https://archive.apache.org/dist/cassandra/4.1.0/apache-cassandra-4.1.0-bin.tar.gz \
        --output apache-cassandra-4.1.0-bin.tar.gz
      tar xf apache-cassandra-4.1.0-bin.tar.gz
      mv apache-cassandra-4.1.0 node1
      cp -r node1/ node2/
      sed -i 's/listen_address: localhost/listen_address: 127.0.0.1/' node1/conf/cassandra.yaml
      sed -i 's/listen_address: localhost/listen_address: 127.0.0.2/' node2/conf/cassandra.yaml
    command: | 
      /workspace/ds201-lab07/node1/bin/cassandra
      /workspace/ds201-lab07/node2/bin/cassandra 
github:
  prebuilds:
    main: true
ports:
  - port: 1-9999
    onOpen: ignore
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix